In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## 00. Pytorch Fundamentals

Resouce notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## INTRODUCTION TO TENSORS

### Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor(
    [[7,8],
     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                                [3,6,9],
                                [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers - > look at data -> update random numbers`

In [ ]:
# creating a rand tensor of shape (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3081, 0.2668, 0.1824, 0.8284],
        [0.7372, 0.7966, 0.9529, 0.7506],
        [0.9646, 0.8838, 0.3393, 0.0417]])

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# creating a rand tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# using torch.arange
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning.

1. Tensors not in right datatype
2. Tensors not in right shape
3. Tensors not on right device

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # datatype of tensor(default = float32)
                               device = None, # what device tensor is on
                               requires_grad=False) # whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not in right datatype -> use `tensor.dtype`
2. Tensors not in right shape -> use `tensor.shape`
3. Tensors not on right device -> use `tensor.device`

In [ ]:
float_32_tensor.device

device(type='cpu')

In [ ]:
float_32_tensor.shape

torch.Size([3])

In [ ]:
float_32_tensor.dtype

torch.float32

### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Muliplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])
tensor = tensor + 10

In [ ]:
# multiply by 10
tensor = tensor * 10
tensor

tensor([110, 120, 130])

In [ ]:
# subtract 10
tensor = tensor - 10
tensor

tensor([100, 110, 120])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More info on matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3,2)` --> `(2,2)`

In [ ]:
# element wise
print(tensor,'*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([100, 110, 120]) * tensor([100, 110, 120])
Equals: tensor([10000, 12100, 14400])


In [ ]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(36500)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 360 µs, sys: 0 ns, total: 360 µs
Wall time: 1.44 ms


tensor(36500)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 201 µs, sys: 0 ns, total: 201 µs
Wall time: 655 µs


tensor(36500)

### One of the most common errors in deep learning is shape errors

In [ ]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B = torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.shape

torch.Size([3, 2])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
# The matrix multiplication works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions sample\some_dir")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)

print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions sample\some_dir
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [ ]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [ ]:
tensor_A.T.shape

torch.Size([2, 3])

In [ ]:
tensor_B.shape

torch.Size([3, 2])

In [ ]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [ ]:
torch.mm(tensor_A.T, tensor_B).shape

torch.Size([2, 2])

## Tensor Aggregation
Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#find the average
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#find max by converting data type from long to float
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
#find the sum
torch.sum(x), x.sum()

### Finding the positional index of min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the index position of min value in tensor
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
# find the index position of max value in tensor
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* `Reshaping` - reshapes an input tensor to a definded shape.
* `View` - return a view of an input tensor of certain shape but keeps the same memory as the original tensor
* `Stacking` - combine multiple tensors on top of each other(vstack) or side-by-side (hstack)
* `Squeeze` - removes all `1` dimensions from a tensor
* `Unsqueeze`- adds a `1` dimension to a target tensor
* `Permute`- return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# reshape - adding an extra dimension
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
x_reshaped = x.reshape(1,2, 5)
x_reshaped, x_reshaped.shape

(tensor([[[ 1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10.]]]),
 torch.Size([1, 2, 5]))

In [ ]:
# view - changing the view
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:

# changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# stacking tensors
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked


tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [ ]:
y = torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [ ]:
x_reshaped.shape

torch.Size([1, 2, 5])

In [ ]:
x_reshaped.squeeze(). shape

torch.Size([2, 5])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[[ 5.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]])
Previous shape: torch.Size([1, 2, 5])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([2, 5])


In [ ]:
# to unsqueeze - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([[ 5.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([2, 5])

New tensor: tensor([[[ 5.,  2.,  3.,  4.,  5.]],

        [[ 6.,  7.,  8.,  9., 10.]]])
New shape: torch.Size([2, 1, 5])


In [ ]:
# permute - rearranges the dimensions of a target tensor in a specified order
x = torch.rand(2,3,5)
x.size()


torch.Size([2, 3, 5])

In [ ]:
torch.permute(x, (2,0,1)).size()

torch.Size([5, 2, 3])

In [ ]:
x_original = torch.rand(size = (224, 224, 3)) #height, width, color_cahnnels
x_permuted = x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 22355
x_original[0,0,0], x_permuted[0,0,0]

(tensor(22355.), tensor(22355.))

### Indexing (Seleting data from arrays)

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,2]

tensor([7, 8, 9])

In [ ]:
x[0,0,2]

tensor(3)

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[0:2]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:,2]

tensor([[7, 8, 9]])

In [ ]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1,1]

tensor([5])

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

### Pytorch tensors & NumPy
NumPy is a popular scientific Python numerical computing theory library, and because of this, PyTorch has functionality to interact with it.
* Data in Numpy, want in PyTorch tensor -. `torch,from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to PyTorch tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of random)
In short, hoiw a neural networks learns is:

`start with rand numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce randomness in neural networks and PyTorch comes the concept of **random seed**. Essentially what the random seed does is "flavour" the randomness.

In [1]:
import torch
#create two rand tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8154, 0.3904, 0.8536, 0.4104],
        [0.9631, 0.1839, 0.8294, 0.8792],
        [0.3765, 0.1791, 0.4189, 0.4115]])

Tensor B:
tensor([[0.1114, 0.5997, 0.7747, 0.7830],
        [0.2434, 0.6016, 0.6658, 0.7085],
        [0.8386, 0.4487, 0.0231, 0.6616]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [2]:
# set random seed reproducible tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Accessing a GPU
Running tensors and PyTorch objects on the GPUs (and making faster computations)
GPUs = faster computation on numbers thanks to CUDA + NVIDIA + PyTorch working behind the scenes to make everything work efficiently.

#### Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure; these services allow you to rent computers on the cloud and access them.

In [1]:
!nvidia-smi

Tue Jul  2 07:57:52 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
torch.cuda.is_available()

True

In [6]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# count number of devices
torch.cuda.device_count()

1

### **Introduction to PyTorch Workflow**
Putting tensors(and model) on the GPU <br>
The reason we want out tensors/models on th GPU is because using a GPU results in faster computations.

In [7]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# moving tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to CPU
If tensor is on GPU, we can't transform it to Numpy

In [9]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [14]:
# to fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])