1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on `torch.Tensor` and for `torch.cuda.`
2. create a random tensor with shape `(7,7)`.
3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).
4. Set the random seed to `0` and do exercises 2 & 3 over again.
5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.
6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).
7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.
10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [2]:
#2 random tensor woth shape(7,7)
import torch
tensor = torch.rand(7,7)
tensor

tensor([[0.0327, 0.7073, 0.1627, 0.6055, 0.8966, 0.9338, 0.4846],
        [0.2012, 0.7735, 0.6791, 0.7102, 0.4897, 0.0427, 0.1517],
        [0.3441, 0.0050, 0.5808, 0.0915, 0.6949, 0.0409, 0.8461],
        [0.9782, 0.5874, 0.4148, 0.8405, 0.8886, 0.0547, 0.2017],
        [0.4323, 0.9783, 0.4886, 0.9284, 0.8151, 0.1287, 0.2520],
        [0.4376, 0.9578, 0.7589, 0.2479, 0.9175, 0.7194, 0.5917],
        [0.2128, 0.4902, 0.7830, 0.0941, 0.0074, 0.4015, 0.9065]])

In [3]:
#3 matrix mul on tensor with another tensor (1,7)
# creating tensor2
tensor2 = torch.rand(1,7)
tensor2

tensor([[0.3299, 0.5346, 0.4557, 0.6193, 0.0789, 0.0286, 0.8168]])

In [5]:
tensor_mul = tensor.matmul(tensor2.T)
tensor_mul

tensor([[1.3313],
        [1.3930],
        [1.1847],
        [1.5827],
        [1.7371],
        [1.7321],
        [1.4998]])

In [7]:
#4 set random seed to 0 and do exercises 2 and 3 again

# setting rand seed
torch.manual_seed(0)
tensor = torch.rand(7,7)

tensor2 = torch.rand(1,7)

tensor_mul = tensor.matmul(tensor2.T)
tensor_mul

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [8]:
#5 set the GPU random seed to 1234
torch.cuda.manual_seed(1234)

In [10]:
# 6 create rand tensors of shape (2,3) and send them both to GPU
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor1 = torch.rand(2,3).to(device)
tensor2 = torch.rand(2,3).to(device)

tensor1, tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [12]:
# 7 perform matrix mul on the tensors you created in 6

tensor_mul = tensor1.matmul(tensor2.permute(1,0))
tensor_mul

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [13]:
#8 find min and max of tensor_mul
tensor_mul.max(), tensor_mul.min()

(tensor(0.5617), tensor(0.3647))

In [14]:
#9 find index of min and max
tensor_mul.argmax(), tensor_mul.argmin()

(tensor(3), tensor(0))

In [26]:
torch.manual_seed(7)
x = torch.rand(1,1,1,10)
y = x.squeeze()


In [24]:
x, x.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [27]:
y, y.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))